22-brews-review-niky/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get '/brews/strongest', to: 'brews#strongest', as: 'strongest'
  resources :brews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

22-brews-review-niky/app/models/brew.rb
class Brew < ApplicationRecord
  # validates :blend_name, presence: true
  # validates :origin, presence: true
  # validates :notes, presence: true
  has_many :purchases
  
  validates :blend_name, :origin, :notes, :presence => true
  validates :strength, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}


end

22-brews-review-niky/app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :brew

  validates :customer_name, presence: true
  validates :price, numericality: {greater_than: 0}
end

22-brews-review-niky/app/controllers/brews_controller.rb
class BrewsController < ApplicationController

  def index
    @brews = Brew.all
  end

  def new
    @brew = Brew.new
  end

  def create
    @brew = Brew.new(brew_params)
    # try to save it to hit the database
    # create, update, save
    # find a way to return true or false for the validity
    # valid?, save, update
    if @brew.save
      flash[:message] = 'Record Created!'
      redirect_to brew_path(@brew)
    else
      render :new
    end
  end

  def show
    @brew = Brew.find(params[:id])
    @purchase = Purchase.new
  end

  def edit
    @brew = Brew.find(params[:id])
  end

  def update
    @brew = Brew.find(params[:id])
    # @brew.attributes = brew_params
    if @brew.update(brew_params)
      # @brew.save
      flash[:message] = 'Record Update!'
      redirect_to @brew
    else
      render :edit
    end
  end

  def strongest
    @brews = Brew.order(strength: :desc).limit(3)
    render :index
  end

  private

  def brew_params
    params.require(:brew).permit!
  end
end

22-brews-review-niky/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(purchase_params)
    if @purchase.save
      redirect_to @purchase.brew
    else
      render :new
    end
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  private
  def purchase_params
    params.require(:purchase).permit!
  end
end

22-brews-review-niky/app/helpers/brews_helper.rb
module BrewsHelper
end

22-brews-review-niky/app/helpers/purchases_helper.rb
module PurchasesHelper
end

22-brews-review-niky/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewsCrew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

22-brews-review-niky/app/views/purchases/new.erb
<h1>New Purchase</h1>


<% if @purchase.errors.any? %>
  You had some errors!
  <ul>
    <% @purchase.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for(@purchase) do |f| %>
  <%= f.label :customer_name %>
  <%= f.text_field :customer_name %>
  <%= f.label :price %>
  <%= f.number_field :price, {step: '.01'} %>
  <%= f.collection_select :brew_id, Brew.all, :id, :blend_name %>
  <%= f.submit %>
<% end %>

<%= link_to 'Go Back to All Brews', brews_path %>

22-brews-review-niky/app/views/purchases/show.erb
<h1>Thanks for your Purchase</h1>

<p>
  <%= @purchase.brew.blend_name %>
</p>

<p>
  $<%= @purchase.price %>
</p>